name: Build wheels

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - windows-2022
        - macos-12

    env:
      CIBW_ARCHS_LINUX: x86_64 i686 aarch64
      CIBW_ARCHS_MACOS: x86_64 universal2
      CIBW_ARCHS_WINDOWS: AMD64 x86 ARM64
      CIBW_BUILD: "cp36-*" "cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*"
      CIBW_BEFORE_BUILD: cython src/*.pyx src/*.pxd -a --cplus -2


    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
